development:
  adapter: postgresql
  encoding: unicode
  database: learn_together_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: learn_together_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: learn_together_production
  pool: 5
  timeout: 5000